server:
  port: 9091  # Gateway will run on this port

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE  # URL of your Product service
          predicates:
            - Path=/api/v1/products/**       # Routes requests starting with /products
        - id: customer-service
          uri: http://customer-service:8080   # Laravel container + port
          predicates:
            - Path=/api/v1/customers/**       # Map gateway path to Laravel
          filters:
            - RewritePath=/api/v1/customers/(?<segment>.*), /$\{segment}